name: Test CI

on: [push, pull_request]

env:
  qemu-version: 10.1.0

jobs:
  app-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, riscv64, aarch64, loongarch64]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: cargo-bin-cache
        cache-targets: false
    - uses: arceos-org/setup-qemu@v1
      with:
        version: ${{ env.qemu-version }}
        arch_list: ${{ matrix.arch }}
    - uses: arceos-org/setup-musl@v1
      with:
        arch: ${{ matrix.arch }}
    - name: Run app tests
      run: |
        make disk_img
        make test ARCH=${{ matrix.arch }}
